### ISSUE TITLE
shasum fail require sudo passowrd.

### ISSUE THREAD

**Issue by Bedotech** [silpion/ansible-java#26]
i use 'silpion/ansible-tomcat' and i install java with this role but i have an error:
```
failed: [machine1 -> localhost] => (item=/usr/bin/shasum) => {"changed": false, "failed": true, "item": "/usr/bin/shasum", "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

this is the task:
```yaml
- name: Register shasum binary
  tags:
    - java
    - java_download
  changed_when: false
  register: java_registered_shasum_binary
  when: java_shasum_binary in (None, "")
  always_run: true
  with_first_found: java_shasum_binaries
  local_action: command true
```
